### ISSUE TITLE
buttonevent of hue tap not updated if pressed twice 

### ISSUE THREAD

**Issue by mswiege** [iobroker-community-adapters/ioBroker.hue#100]
The hue tap is shown in the objects tree with the attributes "buttonevent", "lastupdated" and "on".
If a button is pressed on the device the buttonevent and lastupdated values get updated on the next poll.
But if the same button is pressed again, only the lastupdated value is updated. 
To be able to react on a button being pressed more than once, the buttonevent should be updated also (with the same value as before) if a button was pressed since the last poll from the bridge.

**Comment by foxriver76** [comment]
Probably we only set state if changed, because I was focussing on the lights. However, I don't know the meaning of these datapoints, because I don't use a Hue tap or something similar. So where is the difference between using `lastupdated` or trigger on an update of the dp? The problem which is probably there with the dp update is, that we don't know how long it takes for the hue bridge to set the button back to false after it has been triggered? Thus, with low polling intervals, you maybe will receive a state update if we change the logic, no matter if there has been a real update on the bridge or not.

**Comment by mswiege** [comment]
The polling mechanism and buttons probably just go well together. I don't know the details of what the adapter receives on each poll from the bridge but probably it just receives the last pressed button (`buttonevent`) and therefore doesn't know if this represents the same state as before last poll or if the button was actually pressed again.
I will listen now to `lastupdated` only and trigger my action depending on the buttonevent instead of listening to the buttonevent itself.
It is not really perfect because the reaction time is the polling time in the worst case and I also might miss a button press if two buttons are pressed within the same polling interval. But for my use-case this is good enough.
