### ISSUE TITLE
Objects don't get updated

### ISSUE THREAD

**Issue by Smibser** [iobroker-community-adapters/ioBroker.hue#159]
**Describe the bug**
The objects don't update in ioBroker when I change them in the hue app. Do I have to trigger the update manually?

**To Reproduce**
1. Go to the hue app
2. Create a new room, scene or rename device
3. The change isn't synced to ioBroker

**Expected behavior**
The objects should update in iobroker

**Versions:**
 - Adapter version: 3.3.11

**Comment by micro7** [comment]
I can tell that it had been like that at V 3.3.8 already and it's a feature.
_poll_ function updates or deletes only previously known devices, but it doesn't create any new ones. It's same for sensors, lights and groups (Objects).

**Workaround**
Restart adapter, which will run _connect_ function, which creates new groups etc. as well.

**Potential fix (if supported)**
Keep current loop over known Objects (added to poll_ObjType_ at _connect_ function) retaining _updated_ states, for each new group check if already _updated_, else create.

**Prerequisite**
To stay DRY create group/scene/light Objects by functions (move code from _connect_ function).

**Comment by foxriver76** [comment]
I think it is necessary to restart to get the new devices since the initial version of this adapter. Of course it would be fixable but needs a bit of redesign and more checks at every poll, which of course could have negative impacts running the adapter with very low poll intervals. 

I will think about it.

**Comment by micro7** [comment]
I also imagined that it could be for performance reasons and I am not sure if it's best practice that adapters create new objects at (re)start only (maybe with restarts of adapters controlled by scripts).

Since an extra loop is needed anyway, this could be built conditionally then, meaning to be controlled by admin page + new native boolean createObjOnPoll (default false).

**Comment by foxriver76** [comment]
Normally this is not a problem, but here the problem is pretty much the polling of the api. I run the adapter with a polling interval of 2 seconds to get near real-time updates. This causes the adapter process to be the most cpu hungry process on my system.

However, I will check how such a solution performs the next days. The checkbox would also be an option.

**Comment by foxriver76** [comment]
I have implemented a non-cpu-expensive solution, which should do detect new devices in nearly all cases. For now an adapter restart is initialized to add the new devices. If this turns out to work well, I will split up the handling to avoid the restart
