### ISSUE TITLE
Object 'system.adapter.hue.0.alive' is not available

### ISSUE THREAD

**Issue by tsvsj** [iobroker-community-adapters/ioBroker.hue#65]
Hi,

unfortunately this module didn't create the alive object, which I use to monitor the state of the instances via checkMK. From my understanding, the adapter should have created an alive object, based on the modes description within the developer notes (https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#instance > adapter/instance common.mode). If I understood this correctly, the object 'alive' should be created automatically, as long as the mode is not defined as 'none' or 'once'. As far as I was able to recognize, the instance is running in daemon mode, which should have created the object.

Any idea what could have been go wrong in my installation?

Thanks for any help!

**Comment by eXTreMe-1337** [comment]
Hey, i got the same problem.
After updating from (i think) 1.1.0 to 1.2.3 the adapter contineously trys to start every 30 seconds according to the logfile, but is already running. The status indicator in the iobroker instances tab stays green all the time. So i think it mitght be a problem with the alive value (system.adapter.hue.0.alive), it changes every 15 seconds from true to false an back to true
After downgrading from 1.2.3 back to 1.1.0 the problem still exists.
The adapter is working fine (controlling my hue lamps is still possible), except for the alive value which spams the logfile.
I used the alive value to monitor the hue adapter state and get a push notification if it failes but this is not possible anymore because i'll receive every 30 seconds a notification on my phone.

Here is the Logfile:
`

host.ioBroker-Rock64 | 2019-07-17 10:34:10.836 | info | Restart adapter system.adapter.hue.0 because enabled
-- | -- | -- | --
host.ioBroker-Rock64 | 2019-07-17 10:34:10.835 | error | instance system.adapter.hue.0 terminated with code 7 (Adapter already running)
host.ioBroker-Rock64 | 2019-07-17 10:34:09.225 | info | instance system.adapter.hue.0 started with pid 24236
host.ioBroker-Rock64 | 2019-07-17 10:33:39.146 | info | Restart adapter system.adapter.hue.0 because enabled
host.ioBroker-Rock64 | 2019-07-17 10:33:39.145 | error | instance system.adapter.hue.0 terminated with code 7 (Adapter already running)
host.ioBroker-Rock64 | 2019-07-17 10:33:37.407 | info | instance system.adapter.hue.0 started with pid 23454
host.ioBroker-Rock64 | 2019-07-17 10:33:07.269 | info | Restart adapter system.adapter.hue.0 because enabled
host.ioBroker-Rock64 | 2019-07-17 10:33:07.269 | error | instance system.adapter.hue.0 terminated with code 7 (Adapter already running)

`

**Comment by Apollon77** [comment]
@eXTreMe-1337 No you do not have the same problem. For you there is just a parocess still run ing. Kill manually or reboot to fix that error.
@tsvsj this will be fixed in newer js-controller versions ( I think 1.5.x already when you reinstall the adapter. in 2.0.0 maybe even better

**Comment by darkiop** [comment]
Guten Morgen @tsvsj , ich bin auf der Suche nach einer Möglichkeit Datenpunkte und Instanzen über CheckMK zu überwachen. In deinem ersten Kommentar hast du davon geschrieben, könntest du mir kurz berichten wie du das gelöst hast? Gerne auch im ioBroker-Forum (= selber Nickname).

PS: Sorry für das kapern des Issues hier, aber leider gibts ja keine Message Funktion mehr hier auf Github :)

**Comment by tsvsj** [comment]
@darkiop: Das Problem habe ich damals mit dem Adapter nicht lösen können, sondern habe den alternativen Adapter hue-extended genutzt. Dort gab es das Thema nicht. Bin nicht sicher, ob der Name korrekt ist, weil ich seit einigen Monaten kein ioBroker mehr nutze.

**Comment by darkiop** [comment]
Hi, du hast mich falsch Verstanden :) Meine Frage bezog sich auf "Wie hast du die Daten der States in Checkmk geholt". Ich bin heute allerdings auch weitergekommen und kann die Daten via https://docs.checkmk.com/latest/en/localchecks.html schicken. In meinem Thread im Forum habe ich meinen aktuellen Stand gepostet (https://forum.iobroker.net/topic/44405/checkmk-monitoring-von-iobroker-homematic). Wäre super wenn du dort berichten könntest wie du es bei dir gelöst hast, denn Grundsätzlich ist das ein sehr spannendes Thema ;)
